# Generated by Django 6.1 on 2026-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUCTEUR', 'Producteur'), ('SUPERMARCHE', 'Supermarché'), ('PARTICULIER', 'Particulier')], default='ACHETEUR', max_length=20),
        ),
    ]
