# Generated by Django 6.1 on 2026-08-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUCTEUR', 'Producteur'), ('SUPERMARCHE', 'Supermarché'), ('PARTICULIER', 'Particulier')], default='PARTICULIER', max_length=20),
        ),
    ]
