# Generated by Django 6.1 on 2026-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
