# Generated by Django 6.1 on 2026-08-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commande_frais_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='frais_livraison',
        ),
    ]
